/*******************************************************************************
 * Create Follow-Up Tables (Simplified)
 * Run this in SSMS connected to UnFranchiseMarketing database
 ******************************************************************************/

USE UnFranchiseMarketing;
GO

-- Drop existing tables if they exist
IF OBJECT_ID('dbo.FollowUpReminder', 'U') IS NOT NULL
    DROP TABLE dbo.FollowUpReminder;
GO

IF OBJECT_ID('dbo.FollowUp', 'U') IS NOT NULL
    DROP TABLE dbo.FollowUp;
GO

IF OBJECT_ID('dbo.FollowUpTemplate', 'U') IS NOT NULL
    DROP TABLE dbo.FollowUpTemplate;
GO

-- 1. Follow-Up Templates
CREATE TABLE dbo.FollowUpTemplate (
    TemplateID INT IDENTITY(1,1) NOT NULL,
    TemplateName NVARCHAR(100) NOT NULL,
    Category NVARCHAR(50) NULL,
    Type NVARCHAR(20) NOT NULL DEFAULT 'Call',
    DefaultPriority NVARCHAR(20) NOT NULL DEFAULT 'Medium',
    DefaultNotes NVARCHAR(MAX) NULL,
    DaysAfterShare INT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),
    UpdatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_FollowUpTemplate PRIMARY KEY CLUSTERED (TemplateID),
    CONSTRAINT UQ_FollowUpTemplate_Name UNIQUE (TemplateName)
);
GO

-- 2. Follow-Up Tasks
CREATE TABLE dbo.FollowUp (
    FollowUpID BIGINT IDENTITY(1,1) NOT NULL,
    UserID BIGINT NOT NULL,
    ContactID BIGINT NOT NULL,

    -- Scheduling
    DueDate DATETIME2(7) NOT NULL,
    Priority NVARCHAR(20) NOT NULL DEFAULT 'Medium',

    -- Status
    Status NVARCHAR(20) NOT NULL DEFAULT 'Pending',

    -- Type and Details
    Type NVARCHAR(20) NOT NULL DEFAULT 'Call',
    Notes NVARCHAR(MAX) NULL,

    -- Completion
    CompletedDate DATETIME2(7) NULL,
    CompletedNotes NVARCHAR(MAX) NULL,

    -- Snoozing
    SnoozedUntil DATETIME2(7) NULL,
    SnoozedCount INT NOT NULL DEFAULT 0,

    -- Related Items (nullable foreign keys)
    RelatedShareEventID BIGINT NULL,
    RelatedContentItemID BIGINT NULL,
    CreatedFromTemplateID INT NULL,

    -- Automation
    IsAutoGenerated BIT NOT NULL DEFAULT 0,

    -- Reminders
    ReminderSent BIT NOT NULL DEFAULT 0,
    ReminderSentDate DATETIME2(7) NULL,

    -- Audit
    CreatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),
    UpdatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_FollowUp PRIMARY KEY CLUSTERED (FollowUpID),
    CONSTRAINT FK_FollowUp_User FOREIGN KEY (UserID) REFERENCES dbo.[User](UserID),
    CONSTRAINT FK_FollowUp_Contact FOREIGN KEY (ContactID) REFERENCES dbo.Contact(ContactID),
    CONSTRAINT FK_FollowUp_Template FOREIGN KEY (CreatedFromTemplateID) REFERENCES dbo.FollowUpTemplate(TemplateID),
    CONSTRAINT CK_FollowUp_Priority CHECK (Priority IN ('Low', 'Medium', 'High', 'Urgent')),
    CONSTRAINT CK_FollowUp_Status CHECK (Status IN ('Pending', 'Completed', 'Snoozed', 'Cancelled')),
    CONSTRAINT CK_FollowUp_Type CHECK (Type IN ('Call', 'Email', 'Meeting', 'Task', 'Other'))
);
GO

-- Indexes (without problematic filtered indexes using SYSDATETIME)
CREATE NONCLUSTERED INDEX IX_FollowUp_User_Status ON dbo.FollowUp(UserID, Status, DueDate);
CREATE NONCLUSTERED INDEX IX_FollowUp_User_DueDate ON dbo.FollowUp(UserID, DueDate) WHERE Status = 'Pending';
CREATE NONCLUSTERED INDEX IX_FollowUp_Contact ON dbo.FollowUp(ContactID, Status, DueDate);
CREATE NONCLUSTERED INDEX IX_FollowUp_Priority ON dbo.FollowUp(UserID, Priority, DueDate) WHERE Status = 'Pending';
CREATE NONCLUSTERED INDEX IX_FollowUp_ShareEvent ON dbo.FollowUp(RelatedShareEventID) WHERE RelatedShareEventID IS NOT NULL;
CREATE NONCLUSTERED INDEX IX_FollowUp_Reminder ON dbo.FollowUp(ReminderSent, DueDate) WHERE Status = 'Pending' AND ReminderSent = 0;
GO

-- 3. Follow-Up Reminders
CREATE TABLE dbo.FollowUpReminder (
    ReminderID BIGINT IDENTITY(1,1) NOT NULL,
    FollowUpID BIGINT NOT NULL,
    ReminderDate DATETIME2(7) NOT NULL,
    DeliveryChannel NVARCHAR(20) NOT NULL DEFAULT 'Email',
    Sent BIT NOT NULL DEFAULT 0,
    SentDate DATETIME2(7) NULL,
    ErrorMessage NVARCHAR(MAX) NULL,
    CreatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_FollowUpReminder PRIMARY KEY CLUSTERED (ReminderID),
    CONSTRAINT FK_FollowUpReminder_FollowUp FOREIGN KEY (FollowUpID) REFERENCES dbo.FollowUp(FollowUpID) ON DELETE CASCADE,
    CONSTRAINT CK_FollowUpReminder_Channel CHECK (DeliveryChannel IN ('Email', 'SMS', 'Push', 'InApp'))
);
GO

CREATE NONCLUSTERED INDEX IX_FollowUpReminder_FollowUp ON dbo.FollowUpReminder(FollowUpID);
CREATE NONCLUSTERED INDEX IX_FollowUpReminder_Pending ON dbo.FollowUpReminder(ReminderDate, Sent) WHERE Sent = 0;
GO

PRINT 'Follow-Up tables created successfully!';
GO
