import { query, executeProcedure } from '../config/database.js';
import { createLogger } from '../utils/logger.js';
import {
  FollowUp,
  CreateFollowUpRequest,
  UpdateFollowUpRequest,
  FollowUpFilters,
  FollowUpStats,
  CompleteFollowUpRequest,
  SnoozeFollowUpRequest
} from '../types/followup.types.js';

const logger = createLogger('FollowUpService');

interface DbFollowUp {
  FollowUpID: number;
  UserID: number;
  ContactID: number;
  ContactName?: string;
  ContactEmail?: string;
  ContactMobile?: string;
  DueDate: Date;
  Priority: string;
  Status: string;
  Type: string;
  Notes?: string;
  CompletedDate?: Date;
  CompletedNotes?: string;
  SnoozedUntil?: Date;
  SnoozedCount?: number;
  ReminderSent?: boolean;
  ReminderSentDate?: Date;
  CreatedDate: Date;
  UpdatedDate: Date;
  IsOverdue?: number;
  HoursOverdue?: number;
}

export class FollowUpService {
  /**
   * Create a new follow-up task
   */
  async createFollowUp(followupData: CreateFollowUpRequest, userId: number): Promise<FollowUp> {
    try {
      logger.info(`Creating follow-up for user ${userId}, contact ${followupData.contactId}`);

      const dueDate = new Date(followupData.dueDate);

      const result = await query<{ FollowUpID: number }>(`
        INSERT INTO dbo.FollowUp (
          UserID,
          ContactID,
          DueDate,
          Priority,
          Status,
          Type,
          Notes,
          IsAutoGenerated,
          CreatedDate,
          UpdatedDate
        )
        OUTPUT INSERTED.FollowUpID
        VALUES (
          @userId,
          @contactId,
          @dueDate,
          @priority,
          'Pending',
          @type,
          @notes,
          0,
          SYSDATETIME(),
          SYSDATETIME()
        )
      `, {
        userId,
        contactId: followupData.contactId,
        dueDate,
        priority: followupData.priority,
        type: followupData.type,
        notes: followupData.notes || null
      });

      const followUpId = result[0].FollowUpID;

      // Create reminder for 24 hours before due date
      const reminderDate = new Date(dueDate);
      reminderDate.setHours(reminderDate.getHours() - 24);

      await query(`
        INSERT INTO dbo.FollowUpReminder (
          FollowUpID,
          ReminderDate,
          DeliveryChannel,
          Sent,
          CreatedDate
        )
        VALUES (
          @followUpId,
          @reminderDate,
          'InApp',
          0,
          SYSDATETIME()
        )
      `, { followUpId, reminderDate });

      logger.info(`Follow-up created with ID: ${followUpId}`);

      return await this.getFollowUp(followUpId, userId);
    } catch (error) {
      logger.error('Error creating follow-up:', error);
      throw error;
    }
  }

  /**
   * Get a single follow-up by ID
   */
  async getFollowUp(followUpId: number, userId: number): Promise<FollowUp> {
    try {
      const results = await query<DbFollowUp>(`
        SELECT
          f.FollowUpID,
          f.UserID,
          f.ContactID,
          c.FirstName + ' ' + ISNULL(c.LastName, '') as ContactName,
          c.Email as ContactEmail,
          c.Mobile as ContactMobile,
          f.DueDate,
          f.Priority,
          f.Status,
          f.Type,
          f.Notes,
          f.CompletedDate,
          f.CompletedNotes,
          f.SnoozedUntil,
          f.SnoozedCount,
          f.ReminderSent,
          f.ReminderSentDate,
          f.CreatedDate,
          f.UpdatedDate
        FROM dbo.FollowUp f
        INNER JOIN dbo.Contact c ON f.ContactID = c.ContactID
        WHERE f.FollowUpID = @followUpId AND f.UserID = @userId
      `, { followUpId, userId });

      if (results.length === 0) {
        throw new Error('Follow-up not found or access denied');
      }

      return this.mapDbToFollowUp(results[0]);
    } catch (error) {
      logger.error(`Error getting follow-up ${followUpId}:`, error);
      throw error;
    }
  }

  /**
   * Get follow-ups with filters
   */
  async getFollowUps(userId: number, filters: FollowUpFilters = {}): Promise<{ followUps: FollowUp[]; total: number }> {
    try {
      logger.info(`Getting follow-ups for user ${userId} with filters:`, filters);

      let whereConditions = ['f.UserID = @userId'];
      const params: any = { userId };

      if (filters.contactId) {
        whereConditions.push('f.ContactID = @contactId');
        params.contactId = filters.contactId;
      }

      if (filters.status && filters.status !== 'All') {
        whereConditions.push('f.Status = @status');
        params.status = filters.status;
      }

      if (filters.priority) {
        whereConditions.push('f.Priority = @priority');
        params.priority = filters.priority;
      }

      if (filters.type) {
        whereConditions.push('f.Type = @type');
        params.type = filters.type;
      }

      if (filters.startDate) {
        whereConditions.push('f.DueDate >= @startDate');
        params.startDate = new Date(filters.startDate);
      }

      if (filters.endDate) {
        whereConditions.push('f.DueDate <= @endDate');
        params.endDate = new Date(filters.endDate);
      }

      if (filters.overdue) {
        whereConditions.push('f.DueDate < SYSDATETIME() AND f.Status = \'Pending\'');
      }

      if (filters.upcoming) {
        whereConditions.push('f.DueDate >= SYSDATETIME() AND f.Status = \'Pending\'');
      }

      const whereClause = whereConditions.join(' AND ');
      const limit = filters.limit || 50;
      const offset = filters.offset || 0;

      // Get total count
      const countResult = await query<{ Total: number }>(`
        SELECT COUNT(*) as Total
        FROM dbo.FollowUp f
        WHERE ${whereClause}
      `, params);

      const total = countResult[0].Total;

      // Get follow-ups
      const results = await query<DbFollowUp>(`
        SELECT
          f.FollowUpID,
          f.UserID,
          f.ContactID,
          c.FirstName + ' ' + ISNULL(c.LastName, '') as ContactName,
          c.Email as ContactEmail,
          c.Mobile as ContactMobile,
          f.DueDate,
          f.Priority,
          f.Status,
          f.Type,
          f.Notes,
          f.CompletedDate,
          f.CompletedNotes,
          f.SnoozedUntil,
          f.SnoozedCount,
          f.ReminderSent,
          f.ReminderSentDate,
          f.CreatedDate,
          f.UpdatedDate,
          CASE WHEN f.DueDate < SYSDATETIME() AND f.Status = 'Pending' THEN 1 ELSE 0 END as IsOverdue
        FROM dbo.FollowUp f
        INNER JOIN dbo.Contact c ON f.ContactID = c.ContactID
        WHERE ${whereClause}
        ORDER BY
          CASE WHEN f.DueDate < SYSDATETIME() AND f.Status = 'Pending' THEN 0 ELSE 1 END,
          f.Priority DESC,
          f.DueDate ASC
        OFFSET @offset ROWS
        FETCH NEXT @limit ROWS ONLY
      `, { ...params, offset, limit });

      const followUps = results.map(r => this.mapDbToFollowUp(r));

      logger.info(`Found ${followUps.length} follow-ups (total: ${total})`);

      return { followUps, total };
    } catch (error) {
      logger.error('Error getting follow-ups:', error);
      throw error;
    }
  }

  /**
   * Get upcoming follow-ups (next N days)
   */
  async getUpcomingFollowUps(userId: number, days: number = 7): Promise<FollowUp[]> {
    try {
      logger.info(`Getting upcoming follow-ups for user ${userId} (next ${days} days)`);

      const results = await query<DbFollowUp>(`
        SELECT
          f.FollowUpID,
          f.UserID,
          f.ContactID,
          c.FirstName + ' ' + c.LastName AS ContactName,
          c.Email AS ContactEmail,
          c.Mobile AS ContactMobile,
          f.DueDate,
          f.Priority,
          f.Status,
          f.Type,
          f.Notes,
          f.CompletedDate,
          f.CompletedNotes,
          f.SnoozedUntil,
          f.SnoozedCount,
          f.CreatedDate,
          f.UpdatedDate,
          CASE WHEN f.DueDate < SYSDATETIME() THEN 1 ELSE 0 END AS IsOverdue,
          CASE
            WHEN f.DueDate < SYSDATETIME()
            THEN DATEDIFF(HOUR, f.DueDate, SYSDATETIME())
            ELSE 0
          END AS HoursOverdue
        FROM dbo.FollowUp f
        INNER JOIN dbo.Contact c ON f.ContactID = c.ContactID
        WHERE f.UserID = @userId
          AND f.Status = 'Pending'
          AND f.DueDate <= DATEADD(DAY, @days, SYSDATETIME())
          AND (f.SnoozedUntil IS NULL OR f.SnoozedUntil <= SYSDATETIME())
        ORDER BY f.DueDate ASC
      `, {
        userId,
        days
      });

      return results.map(r => this.mapDbToFollowUp(r));
    } catch (error) {
      logger.error('Error getting upcoming follow-ups:', error);
      throw error;
    }
  }

  /**
   * Get overdue follow-ups
   */
  async getOverdueFollowUps(userId: number): Promise<FollowUp[]> {
    try {
      logger.info(`Getting overdue follow-ups for user ${userId}`);

      const results = await query<DbFollowUp>(`
        SELECT
          f.FollowUpID,
          f.UserID,
          f.ContactID,
          c.FirstName + ' ' + c.LastName AS ContactName,
          c.Email AS ContactEmail,
          c.Mobile AS ContactMobile,
          f.DueDate,
          f.Priority,
          f.Status,
          f.Type,
          f.Notes,
          f.CompletedDate,
          f.CompletedNotes,
          f.SnoozedUntil,
          f.SnoozedCount,
          f.CreatedDate,
          f.UpdatedDate,
          1 AS IsOverdue,
          DATEDIFF(HOUR, f.DueDate, SYSDATETIME()) AS HoursOverdue
        FROM dbo.FollowUp f
        INNER JOIN dbo.Contact c ON f.ContactID = c.ContactID
        WHERE f.UserID = @userId
          AND f.Status = 'Pending'
          AND f.DueDate < SYSDATETIME()
          AND (f.SnoozedUntil IS NULL OR f.SnoozedUntil <= SYSDATETIME())
        ORDER BY f.DueDate ASC
      `, {
        userId
      });

      return results.map(r => this.mapDbToFollowUp(r));
    } catch (error) {
      logger.error('Error getting overdue follow-ups:', error);
      throw error;
    }
  }

  /**
   * Update a follow-up
   */
  async updateFollowUp(followUpId: number, updates: UpdateFollowUpRequest, userId: number): Promise<FollowUp> {
    try {
      logger.info(`Updating follow-up ${followUpId} for user ${userId}`);

      // Build dynamic update query
      const setClauses: string[] = [];
      const params: any = { followUpId, userId };

      if (updates.dueDate !== undefined) {
        setClauses.push('DueDate = @dueDate');
        params.dueDate = new Date(updates.dueDate);
      }

      if (updates.priority !== undefined) {
        setClauses.push('Priority = @priority');
        params.priority = updates.priority;
      }

      if (updates.status !== undefined) {
        setClauses.push('Status = @status');
        params.status = updates.status;
      }

      if (updates.type !== undefined) {
        setClauses.push('Type = @type');
        params.type = updates.type;
      }

      if (updates.notes !== undefined) {
        setClauses.push('Notes = @notes');
        params.notes = updates.notes;
      }

      setClauses.push('UpdatedDate = SYSDATETIME()');

      if (setClauses.length === 1) {
        throw new Error('No valid fields to update');
      }

      await query(`
        UPDATE dbo.FollowUp
        SET ${setClauses.join(', ')}
        WHERE FollowUpID = @followUpId AND UserID = @userId
      `, params);

      logger.info(`Follow-up ${followUpId} updated successfully`);

      return await this.getFollowUp(followUpId, userId);
    } catch (error) {
      logger.error(`Error updating follow-up ${followUpId}:`, error);
      throw error;
    }
  }

  /**
   * Complete a follow-up
   */
  async completeFollowUp(followUpId: number, userId: number, completionData?: CompleteFollowUpRequest): Promise<FollowUp> {
    try {
      logger.info(`Completing follow-up ${followUpId} for user ${userId}`);

      await query(`
        UPDATE dbo.FollowUp
        SET
          Status = 'Completed',
          CompletedDate = SYSDATETIME(),
          CompletedNotes = @notes,
          UpdatedDate = SYSDATETIME()
        WHERE FollowUpID = @followUpId AND UserID = @userId
      `, {
        followUpId,
        userId,
        notes: completionData?.notes || null
      });

      // Update contact's last contact date
      await query(`
        UPDATE c
        SET
          LastContactDate = SYSDATETIME(),
          UpdatedDate = SYSDATETIME()
        FROM dbo.Contact c
        INNER JOIN dbo.FollowUp f ON c.ContactID = f.ContactID
        WHERE f.FollowUpID = @followUpId
      `, { followUpId });

      logger.info(`Follow-up ${followUpId} completed successfully`);

      return await this.getFollowUp(followUpId, userId);
    } catch (error) {
      logger.error(`Error completing follow-up ${followUpId}:`, error);
      throw error;
    }
  }

  /**
   * Snooze a follow-up to a new date
   */
  async snoozeFollowUp(followUpId: number, snoozeData: SnoozeFollowUpRequest, userId: number): Promise<FollowUp> {
    try {
      logger.info(`Snoozing follow-up ${followUpId} to ${snoozeData.newDueDate}`);

      const newDueDate = new Date(snoozeData.newDueDate);

      await query(`
        UPDATE dbo.FollowUp
        SET
          DueDate = @newDueDate,
          Status = 'Snoozed',
          SnoozedUntil = @newDueDate,
          SnoozedCount = SnoozedCount + 1,
          UpdatedDate = SYSDATETIME()
        WHERE FollowUpID = @followUpId AND UserID = @userId
      `, {
        followUpId,
        userId,
        newDueDate
      });

      // Update reminder date
      await query(`
        UPDATE dbo.FollowUpReminder
        SET
          ReminderDate = DATEADD(HOUR, -24, @newDueDate),
          Sent = 0,
          SentDate = NULL
        WHERE FollowUpID = @followUpId AND Sent = 0
      `, {
        followUpId,
        newDueDate
      });

      logger.info(`Follow-up ${followUpId} snoozed successfully`);

      return await this.getFollowUp(followUpId, userId);
    } catch (error) {
      logger.error(`Error snoozing follow-up ${followUpId}:`, error);
      throw error;
    }
  }

  /**
   * Delete a follow-up
   */
  async deleteFollowUp(followUpId: number, userId: number): Promise<boolean> {
    try {
      logger.info(`Deleting follow-up ${followUpId} for user ${userId}`);

      await query(`
        DELETE FROM dbo.FollowUp
        WHERE FollowUpID = @followUpId AND UserID = @userId
      `, { followUpId, userId });

      logger.info(`Follow-up ${followUpId} deleted successfully`);

      return true;
    } catch (error) {
      logger.error(`Error deleting follow-up ${followUpId}:`, error);
      throw error;
    }
  }

  /**
   * Create automated follow-up after share event
   */
  async createAutomatedFollowUp(
    contactId: number,
    contentId: number,
    userId: number,
    shareEventId?: number,
    defaultDays: number = 3
  ): Promise<FollowUp> {
    try {
      logger.info(`Creating automated follow-up for contact ${contactId}, content ${contentId}`);

      const result = await executeProcedure<{ FollowUpID: number }>('dbo.sp_CreateAutomatedFollowUp', {
        ShareEventID: shareEventId || null,
        ContactID: contactId,
        UserID: userId,
        ContentItemID: contentId,
        DefaultDays: defaultDays
      });

      const followUpId = result[0].FollowUpID;

      logger.info(`Automated follow-up created with ID: ${followUpId}`);

      return await this.getFollowUp(followUpId, userId);
    } catch (error) {
      logger.error('Error creating automated follow-up:', error);
      throw error;
    }
  }

  /**
   * Get follow-up statistics for a user
   */
  async getFollowUpStats(userId: number): Promise<FollowUpStats> {
    try {
      logger.info(`Getting follow-up stats for user ${userId}`);

      const statsResult = await query<any>(`
        SELECT
          COUNT(CASE WHEN Status = 'Pending' THEN 1 END) as TotalPending,
          COUNT(CASE WHEN Status = 'Pending' AND DueDate < SYSDATETIME() THEN 1 END) as TotalOverdue,
          COUNT(CASE WHEN Status = 'Completed' THEN 1 END) as TotalCompleted,
          COUNT(CASE WHEN Status = 'Completed' AND CAST(CompletedDate AS DATE) = CAST(SYSDATETIME() AS DATE) THEN 1 END) as CompletedToday,
          COUNT(CASE WHEN Status = 'Cancelled' THEN 1 END) as TotalCancelled,
          COUNT(CASE WHEN Status = 'Pending' AND CAST(DueDate AS DATE) = CAST(SYSDATETIME() AS DATE) THEN 1 END) as UpcomingToday,
          COUNT(CASE WHEN Status = 'Pending' AND DueDate BETWEEN SYSDATETIME() AND DATEADD(DAY, 7, SYSDATETIME()) THEN 1 END) as UpcomingThisWeek,
          AVG(CASE WHEN Status = 'Completed' THEN DATEDIFF(HOUR, CreatedDate, CompletedDate) END) as AvgCompletionTime
        FROM dbo.FollowUp
        WHERE UserID = @userId
      `, { userId });

      const byPriorityResult = await query<any>(`
        SELECT Priority, COUNT(*) as Count
        FROM dbo.FollowUp
        WHERE UserID = @userId AND Status = 'Pending'
        GROUP BY Priority
      `, { userId });

      const byTypeResult = await query<any>(`
        SELECT Type, COUNT(*) as Count
        FROM dbo.FollowUp
        WHERE UserID = @userId AND Status = 'Pending'
        GROUP BY Type
      `, { userId });

      const stats = statsResult[0];
      const totalTasks = stats.TotalPending + stats.TotalCompleted + stats.TotalCancelled;
      const completionRate = totalTasks > 0 ? (stats.TotalCompleted / totalTasks) * 100 : 0;

      return {
        totalPending: stats.TotalPending || 0,
        totalOverdue: stats.TotalOverdue || 0,
        totalCompleted: stats.TotalCompleted || 0,
        completedToday: stats.CompletedToday || 0,
        totalCancelled: stats.TotalCancelled || 0,
        upcomingToday: stats.UpcomingToday || 0,
        upcomingThisWeek: stats.UpcomingThisWeek || 0,
        completionRate: Math.round(completionRate),
        averageCompletionTime: stats.AvgCompletionTime || 0,
        byPriority: byPriorityResult.map(r => ({ priority: r.Priority, count: r.Count })),
        byType: byTypeResult.map(r => ({ type: r.Type, count: r.Count }))
      };
    } catch (error) {
      logger.error('Error getting follow-up stats:', error);
      throw error;
    }
  }

  /**
   * Map database result to FollowUp type
   */
  private mapDbToFollowUp(db: DbFollowUp): FollowUp {
    return {
      followUpId: db.FollowUpID,
      userId: db.UserID,
      contactId: db.ContactID,
      contactName: db.ContactName,
      contactEmail: db.ContactEmail,
      contactMobile: db.ContactMobile,
      dueDate: db.DueDate,
      priority: db.Priority as any,
      status: db.Status as any,
      type: db.Type as any,
      notes: db.Notes,
      completedDate: db.CompletedDate,
      completedNotes: db.CompletedNotes,
      snoozedUntil: db.SnoozedUntil,
      snoozedCount: db.SnoozedCount,
      reminderSent: db.ReminderSent,
      reminderSentDate: db.ReminderSentDate,
      createdDate: db.CreatedDate,
      updatedDate: db.UpdatedDate
    };
  }
}

export default new FollowUpService();
