/*******************************************************************************
 * UnFranchise Marketing App - Database Schema
 * Microsoft SQL Server 2019+
 *
 * Part 9: Follow-up System
 *
 * Author: Database Architecture Team
 * Created: 2026-04-05
 ******************************************************************************/

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/*******************************************************************************
 * 1. FOLLOW-UP TEMPLATES
 ******************************************************************************/

CREATE TABLE dbo.FollowUpTemplate (
    TemplateID INT IDENTITY(1,1) NOT NULL,
    TemplateName NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,

    -- Default Settings
    DefaultDays INT NOT NULL DEFAULT 3,              -- Days after initial contact
    DefaultPriority NVARCHAR(20) NOT NULL DEFAULT 'Medium', -- Low, Medium, High, Urgent
    DefaultType NVARCHAR(20) NOT NULL DEFAULT 'Call', -- Call, Email, Meeting, Task, Other

    SuggestedAction NVARCHAR(MAX) NULL,              -- Suggested notes/action for UFO

    -- Template Category
    Category NVARCHAR(50) NULL,                      -- Product, Business, Event, NoResponse, ThankYou

    -- Status
    IsActive BIT NOT NULL DEFAULT 1,

    -- Audit
    CreatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),
    UpdatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_FollowUpTemplate PRIMARY KEY CLUSTERED (TemplateID),
    CONSTRAINT UQ_FollowUpTemplate_Name UNIQUE (TemplateName)
);
GO

CREATE NONCLUSTERED INDEX IX_FollowUpTemplate_Active ON dbo.FollowUpTemplate(IsActive, Category);
GO

/*******************************************************************************
 * 2. FOLLOW-UP TASKS
 ******************************************************************************/

CREATE TABLE dbo.FollowUp (
    FollowUpID BIGINT IDENTITY(1,1) NOT NULL,
    UserID BIGINT NOT NULL,                          -- UFO who needs to follow up
    ContactID BIGINT NOT NULL,                       -- Contact to follow up with

    -- Scheduling
    DueDate DATETIME2(7) NOT NULL,
    Priority NVARCHAR(20) NOT NULL DEFAULT 'Medium', -- Low, Medium, High, Urgent

    -- Status
    Status NVARCHAR(20) NOT NULL DEFAULT 'Pending',  -- Pending, Completed, Snoozed, Cancelled

    -- Type and Details
    Type NVARCHAR(20) NOT NULL DEFAULT 'Call',       -- Call, Email, Meeting, Task, Other
    Notes NVARCHAR(MAX) NULL,                        -- UFO's notes about what to do

    -- Completion
    CompletedDate DATETIME2(7) NULL,
    CompletedNotes NVARCHAR(MAX) NULL,               -- What happened when completed

    -- Snooze Tracking
    SnoozedUntil DATETIME2(7) NULL,
    SnoozedCount INT NOT NULL DEFAULT 0,

    -- Related Entities
    RelatedShareEventID BIGINT NULL,                 -- If created from a share
    RelatedContentItemID BIGINT NULL,                -- Content that was shared
    CreatedFromTemplateID INT NULL,                  -- If created from template

    -- Automation
    IsAutoGenerated BIT NOT NULL DEFAULT 0,          -- True if system-created

    -- Reminders
    ReminderSent BIT NOT NULL DEFAULT 0,
    ReminderSentDate DATETIME2(7) NULL,

    -- Audit
    CreatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),
    UpdatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_FollowUp PRIMARY KEY CLUSTERED (FollowUpID),
    CONSTRAINT FK_FollowUp_User FOREIGN KEY (UserID) REFERENCES dbo.[User](UserID),
    CONSTRAINT FK_FollowUp_Contact FOREIGN KEY (ContactID) REFERENCES dbo.Contact(ContactID),
    CONSTRAINT FK_FollowUp_ShareEvent FOREIGN KEY (RelatedShareEventID) REFERENCES dbo.ShareEvent(ShareEventID),
    CONSTRAINT FK_FollowUp_ContentItem FOREIGN KEY (RelatedContentItemID) REFERENCES dbo.ContentItem(ContentItemID),
    CONSTRAINT FK_FollowUp_Template FOREIGN KEY (CreatedFromTemplateID) REFERENCES dbo.FollowUpTemplate(TemplateID),
    CONSTRAINT CK_FollowUp_Priority CHECK (Priority IN ('Low', 'Medium', 'High', 'Urgent')),
    CONSTRAINT CK_FollowUp_Status CHECK (Status IN ('Pending', 'Completed', 'Snoozed', 'Cancelled')),
    CONSTRAINT CK_FollowUp_Type CHECK (Type IN ('Call', 'Email', 'Meeting', 'Task', 'Other'))
);
GO

CREATE NONCLUSTERED INDEX IX_FollowUp_User_Status ON dbo.FollowUp(UserID, Status, DueDate);
CREATE NONCLUSTERED INDEX IX_FollowUp_User_DueDate ON dbo.FollowUp(UserID, DueDate) WHERE Status = 'Pending';
CREATE NONCLUSTERED INDEX IX_FollowUp_Contact ON dbo.FollowUp(ContactID, Status, DueDate);
CREATE NONCLUSTERED INDEX IX_FollowUp_Priority ON dbo.FollowUp(UserID, Priority, DueDate) WHERE Status = 'Pending';
CREATE NONCLUSTERED INDEX IX_FollowUp_Overdue ON dbo.FollowUp(UserID, DueDate)
    WHERE Status = 'Pending' AND DueDate < SYSDATETIME();
CREATE NONCLUSTERED INDEX IX_FollowUp_ShareEvent ON dbo.FollowUp(RelatedShareEventID) WHERE RelatedShareEventID IS NOT NULL;
CREATE NONCLUSTERED INDEX IX_FollowUp_Reminder ON dbo.FollowUp(ReminderSent, DueDate)
    WHERE Status = 'Pending' AND ReminderSent = 0;
GO

/*******************************************************************************
 * 3. FOLLOW-UP REMINDERS
 ******************************************************************************/

CREATE TABLE dbo.FollowUpReminder (
    ReminderID BIGINT IDENTITY(1,1) NOT NULL,
    FollowUpID BIGINT NOT NULL,

    -- Reminder Details
    ReminderDate DATETIME2(7) NOT NULL,              -- When to send reminder
    DeliveryChannel NVARCHAR(20) NOT NULL DEFAULT 'InApp', -- InApp, Email, SMS, Push

    -- Status
    Sent BIT NOT NULL DEFAULT 0,
    SentDate DATETIME2(7) NULL,
    DeliveryStatus NVARCHAR(20) NULL,                -- Pending, Sent, Failed
    FailureReason NVARCHAR(500) NULL,

    -- Audit
    CreatedDate DATETIME2(7) NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_FollowUpReminder PRIMARY KEY CLUSTERED (ReminderID),
    CONSTRAINT FK_FollowUpReminder_FollowUp FOREIGN KEY (FollowUpID) REFERENCES dbo.FollowUp(FollowUpID) ON DELETE CASCADE
);
GO

CREATE NONCLUSTERED INDEX IX_FollowUpReminder_FollowUp ON dbo.FollowUpReminder(FollowUpID);
CREATE NONCLUSTERED INDEX IX_FollowUpReminder_Pending ON dbo.FollowUpReminder(ReminderDate, Sent)
    WHERE Sent = 0;
GO

/*******************************************************************************
 * 4. UPDATE CONTACT TABLE - Add NextFollowUpDate
 ******************************************************************************/

-- Add NextFollowUpDate to Contact table if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.Contact') AND name = 'NextFollowUpDate')
BEGIN
    ALTER TABLE dbo.Contact
    ADD NextFollowUpDate DATETIME2(7) NULL;

    CREATE NONCLUSTERED INDEX IX_Contact_NextFollowUp ON dbo.Contact(OwnerUserID, NextFollowUpDate)
        WHERE NextFollowUpDate IS NOT NULL AND Status = 'Active';
END
GO

/*******************************************************************************
 * 5. STORED PROCEDURES
 ******************************************************************************/

-- Get Upcoming Follow-ups for a User
CREATE OR ALTER PROCEDURE dbo.sp_GetUpcomingFollowUps
    @UserID BIGINT,
    @Days INT = 7
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        f.FollowUpID,
        f.UserID,
        f.ContactID,
        c.FirstName + ' ' + ISNULL(c.LastName, '') as ContactName,
        c.Email as ContactEmail,
        c.Mobile as ContactMobile,
        f.DueDate,
        f.Priority,
        f.Status,
        f.Type,
        f.Notes,
        f.CompletedDate,
        f.CompletedNotes,
        f.SnoozedUntil,
        f.SnoozedCount,
        f.ReminderSent,
        f.ReminderSentDate,
        f.CreatedDate,
        f.UpdatedDate,
        CASE
            WHEN f.DueDate < SYSDATETIME() THEN 1
            ELSE 0
        END as IsOverdue
    FROM dbo.FollowUp f
    INNER JOIN dbo.Contact c ON f.ContactID = c.ContactID
    WHERE
        f.UserID = @UserID
        AND f.Status = 'Pending'
        AND f.DueDate <= DATEADD(DAY, @Days, SYSDATETIME())
    ORDER BY f.DueDate ASC, f.Priority DESC;
END
GO

-- Get Overdue Follow-ups
CREATE OR ALTER PROCEDURE dbo.sp_GetOverdueFollowUps
    @UserID BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        f.FollowUpID,
        f.UserID,
        f.ContactID,
        c.FirstName + ' ' + ISNULL(c.LastName, '') as ContactName,
        c.Email as ContactEmail,
        c.Mobile as ContactMobile,
        f.DueDate,
        f.Priority,
        f.Status,
        f.Type,
        f.Notes,
        f.CompletedDate,
        f.CompletedNotes,
        f.SnoozedUntil,
        f.SnoozedCount,
        f.ReminderSent,
        f.ReminderSentDate,
        f.CreatedDate,
        f.UpdatedDate,
        DATEDIFF(HOUR, f.DueDate, SYSDATETIME()) as HoursOverdue
    FROM dbo.FollowUp f
    INNER JOIN dbo.Contact c ON f.ContactID = c.ContactID
    WHERE
        f.UserID = @UserID
        AND f.Status = 'Pending'
        AND f.DueDate < SYSDATETIME()
    ORDER BY f.Priority DESC, f.DueDate ASC;
END
GO

-- Create Automated Follow-up after Share
CREATE OR ALTER PROCEDURE dbo.sp_CreateAutomatedFollowUp
    @ShareEventID BIGINT,
    @ContactID BIGINT,
    @UserID BIGINT,
    @ContentItemID BIGINT,
    @DefaultDays INT = 3
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @DueDate DATETIME2(7) = DATEADD(DAY, @DefaultDays, SYSDATETIME());

    INSERT INTO dbo.FollowUp (
        UserID,
        ContactID,
        DueDate,
        Priority,
        Status,
        Type,
        Notes,
        RelatedShareEventID,
        RelatedContentItemID,
        IsAutoGenerated,
        CreatedDate,
        UpdatedDate
    )
    VALUES (
        @UserID,
        @ContactID,
        @DueDate,
        'Medium',
        'Pending',
        'Call',
        'Follow up on shared content',
        @ShareEventID,
        @ContentItemID,
        1,
        SYSDATETIME(),
        SYSDATETIME()
    );

    DECLARE @FollowUpID BIGINT = SCOPE_IDENTITY();

    -- Update Contact's NextFollowUpDate
    UPDATE dbo.Contact
    SET NextFollowUpDate = @DueDate,
        UpdatedDate = SYSDATETIME()
    WHERE ContactID = @ContactID;

    -- Create reminder for 24 hours before
    INSERT INTO dbo.FollowUpReminder (
        FollowUpID,
        ReminderDate,
        DeliveryChannel,
        CreatedDate
    )
    VALUES (
        @FollowUpID,
        DATEADD(HOUR, -24, @DueDate),
        'InApp',
        SYSDATETIME()
    );

    SELECT @FollowUpID as FollowUpID;
END
GO

-- Update Contact NextFollowUpDate Trigger
CREATE OR ALTER TRIGGER tr_FollowUp_UpdateContactNextFollowUp
ON dbo.FollowUp
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    -- Get affected contacts
    DECLARE @AffectedContacts TABLE (ContactID BIGINT);

    INSERT INTO @AffectedContacts
    SELECT DISTINCT ContactID FROM inserted
    UNION
    SELECT DISTINCT ContactID FROM deleted;

    -- Update NextFollowUpDate for each affected contact
    UPDATE c
    SET NextFollowUpDate = (
        SELECT MIN(DueDate)
        FROM dbo.FollowUp
        WHERE ContactID = c.ContactID
            AND Status = 'Pending'
    ),
    UpdatedDate = SYSDATETIME()
    FROM dbo.Contact c
    WHERE c.ContactID IN (SELECT ContactID FROM @AffectedContacts);
END
GO

PRINT 'Follow-up schema created successfully';
GO
